services:
  taeketmaster_db:
    image: postgres:17
    container_name: taeketmaster_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-taeketmaster_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/sql:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d taeketmaster_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: tae.admin@tae.ac.th
      PGADMIN_DEFAULT_PASSWORD: tae123
    ports:
      - "5050:80"
    depends_on:
      taeketmaster_db:
        condition: service_healthy
    restart: always

volumes:
  postgres_data: